version: '3.9'
services:
    application-gateway:
        container_name: gateway
        build:
            context: ../api-gateway
        restart: always
        environment:
            KONG_DATABASE: "off"
            KONG_AUTH_KEY: kong-key-auth
            KONG_DECLARATIVE_CONFIG: /home/kong/kong.yml
            KONG_PROXY_ACCESS_LOG: /dev/stdout
            KONG_ADMIN_ACCESS_LOG: /dev/stdout
            KONG_PROXY_ERROR_LOG: /dev/stderr
            KONG_ADMIN_ERROR_LOG: /dev/stderr
            KONG_LOG_LEVEL: debug
            KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
            KONG_PLUGINSERVER_NAMES: js
            KONG_PLUGINSERVER_JS_SOCKET: /usr/local/kong/js_pluginserver.sock
            KONG_PLUGINSERVER_JS_START_CMD: /usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver -v -d /usr/local/kong/js-plugins
            KONG_PLUGINSERVER_JS_QUERY_CMD: /usr/local/lib/node_modules/kong-pdk/bin/kong-js-pluginserver -d /usr/local/kong/js-plugins --dump-all-plugins
            KONG_PLUGINS: bundled, user-authentication, strip-path
        ports:
            - 8000:8000
            - 8443:8443
            - 8001:8001
            - 8444:8444
        networks:
            - application-gateway
            - access-control-network
        depends_on:
            access-control-server:
                condition: service_healthy
        stdin_open: true
        tty: true

    access-control-server:
        container_name: access-control-server
        build:
            dockerfile: dockerfiles/Dockerfile.dev
            context: access-control-server
        env_file:
            - ../.env/auth-dev.env
        volumes:
            - /app/node_modules
            - ./access-control-server:/app
        ports:
            - 49200
        networks:
            - access-control-network
        healthcheck:
            test: wget --no-verbose --tries=1 --spider http://access-control-server:49200 || exit 1
            start_period: 15s
            interval: 5s
            timeout: 10s
            retries: 10

networks:
    application-gateway:
        driver: bridge
    access-control-network:
        driver: bridge
